languageCode = "en-us"
ignoreFiles = [ "\\.files/README.md$",  ]
defaultContentLanguage = "en"
title = "Amazon App Mesh Workshop"
theme = "learn"
uglyurls = false
# googleAnalytics = "UA-44634850-6"
sectionPagesMenu = "main"
relativeURLs = true

[blackfriday]
hrefTargetBlank = true

[params]
editURL = "https://github.com/brentley/appmeshworkshop/edit/master/content/"
themeVariant = "mine"
showVisitedLinks = false
author = "Brent Langston"
description = "Amazon App Mesh Workshop"
disableSearch = false
disableAssetsBusting = false
disableLanguageSwitchingButton = true
disableShortcutsTitle=false
disableInlineCopyToClipBoard = true
ghrepo = "https://github.com/brentley/appmeshworkshop/"
branch = "master"
template_bucket = "appmeshworkshop.com"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "tango"



#

[menu]
  [[menu.main]]
    identifier = "Prerequisites"
    name = "This is the Mu track"
    title = "Workshop using Mu"
    url = "/mu/"
    weight = -110

[[menu.shortcuts]]
name = "<i class='fas fa-bookmark'></i> More Resources"
url = "/more_resources"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-users'></i> Authors"
url = "/authors"
weight = 20

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> GitHub Project"
url = "https://github.com/brentley/appmeshworkshop"
weight = 30

[[menu.shortcuts]]
name = "<i class='fas fa-envelope'></i> Have questions?"
url = "mailto:appmeshworkshop@amazon.com"
weight = 40

[[menu.shortcuts]]
name = "<i class='fas fa-chalkboard'></i> EKS Workshop"
url = "https://eksworkshop.com"
weight = 6

[[menu.shortcuts]]
name = "<i class='fas fa-chalkboard'></i> ECS Workshop"
url = "https://ecsworkshop.com"
weight = 7

[[menu.shortcuts]]
name = "<i class='fas fa-chalkboard'></i> AWS Partner Workshops"
url = "https://awsworkshop.io"
weight = 8

[outputs]
home = [ "HTML", "JSON"]
page = [ "HTML" ]
