---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/introduction
  label: Introduction
  create: all
  match: "**/*"
- type: directory
  path: content/prerequisites
  label: Prerequisites
  create: all
  match: "**/*"
- type: directory
  path: content/deploy
  label: Deploy
  create: all
  match: "**/*"
- type: directory
  path: content/servicemesh_with_appmesh
  label: Servicemesh with appmesh
  create: all
  match: "**/*"
- type: directory
  path: content/x-ray
  label: X ray
  create: all
  match: "**/*"
- type: directory
  path: content/cleanup
  label: Cleanup
  create: all
  match: "**/*"
- type: directory
  path: content/conclusion
  label: Conclusion
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: static
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.55.6
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.55.6
